stages:
  - test
  - deploy

test:
  image: node:10.15-alpine
  stage: test
  variables:
    NODE_ENV: test
    DATABASE_TEST_URL: "mongodb://mongo/dbname"
  services:
    - mongo
  cache:
#    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - apk add make gcc g++ python git
    - npm ci
    - npm run audit
    - npm run lint
    - npm run test:cov
  tags:
    - docker
  only:
    - merge_requests
    - web


.deploy:
  stage: deploy
  variables:
    NODE_ENV: production
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker-compose -p 699-sdcoin up -d

develop:
  extends: .deploy
  environment:
    name: develop
    url:  https://699-sdcoin.pixelplex-test.by/
  variables:
    NODE_APP_INSTANCE: develop
  only:
    - develop
  tags:
    - pp-develop


master:
  extends: .deploy
  environment:
    name: master
    url:  https://699-sdcoin.pixelplexlabs.com/
  variables:
    NODE_APP_INSTANCE: master
  only:
    - master
  tags:
    - pp-stage
