version: '3'

services:

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
    logging:
      driver: none
    ports:
      - 127.0.0.1:26997:27017
    volumes:
      - mongodb:/data/db
    restart: always

  server:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    environment:
      - NODE_ENV=production
      - NODE_APP_INSTANCE=$NODE_APP_INSTANCE
      - MONGODB_URI=mongodb://mongodb:27017/
      - CRYPTO_API_TOKEN=$CRYPTO_API_TOKEN
    ports:
      - "26991:3000"
      - "26992:3001"
    restart: always
    depends_on:
      - mongodb

volumes:
  mongodb:
