version: '3'

services:

  mongodb:
    image: mongo:latest

    environment:
      - MONGO_DATA_DIR=/data/db
    logging:
      driver: none
    ports:
      - 127.0.0.1:26997:27017
    volumes:
      - mongodb:/data/db
    restart: always

  server:
    build: .
    command: npm run start:dev
    volumes:
      - ./src:/app/src/
      - ./config:/app/config
    environment:
      - NODE_APP_INSTANCE=develop
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - mongodb

  server_migrate:
    build: .
    command: npm run migrate
    depends_on:
      - "mongodb"
    environment:
      - NODE_APP_INSTANCE=develop
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/
volumes:
  mongodb:
